// license-api.js
// Express routes. These are the ONLY place that decides if a device may run DMS POS.
// The desktop client never decides this itself — it only asks and verifies the signed answer.

const express = require('express');
const crypto = require('crypto');
const { v4: uuidv4 } = require('uuid');
const { signVerdict } = require('./crypto-utils');
// `db` = your mysql2/pool wrapper — adapt to whatever the rest of DMS already uses.
const db = require('./db');

const router = express.Router();

const GRACE_PERIOD_HOURS = 48; // max time client can run without contacting server

// Wraps an async route handler so a thrown/rejected error becomes a clean 500
// response instead of an unhandled promise rejection that crashes the whole
// Node process (which is what was happening before — any transient DB hiccup
// took the entire server down, causing Render to restart it and every request
// hitting it mid-restart to see a 502).
function asyncRoute(handler) {
  return (req, res, next) => {
    Promise.resolve(handler(req, res, next)).catch((err) => {
      console.error('[license-api] error:', err.message);
      if (!res.headersSent) res.status(500).json({ error: 'internal_error' });
    });
  };
}

/**
 * POST /license/register
 * First run on a new device. Registers hw_fingerprint, creates a trial license
 * if this fingerprint has never been seen before (blocks "reinstall = new trial").
 */
router.post('/license/register', asyncRoute(async (req, res) => {
  const { hw_fingerprint, device_id_hint } = req.body;
  if (!hw_fingerprint) return res.status(400).json({ error: 'hw_fingerprint required' });

  // 1. Has this HARDWARE been seen before? (not "does this device_id exist" — device_id
  //    can be regenerated by the client, hw_fingerprint mostly cannot)
  let device = await db.query('SELECT * FROM devices WHERE hw_fingerprint = ?', [hw_fingerprint]);

  if (device.length === 0) {
    const device_id = device_id_hint || uuidv4();
    await db.query(
      'INSERT INTO devices (device_id, hw_fingerprint) VALUES (?, ?)',
      [device_id, hw_fingerprint]
    );
    const license_id = uuidv4();
    await db.query(
      `INSERT INTO licenses (license_id, device_id, plan_type, trial_started_at, trial_days, status)
       VALUES (?, ?, 'trial', NOW(), 3, 'active')`,
      [license_id, device_id]
    );
    device = [{ device_id }];
  }
  // If hw_fingerprint already existed, we deliberately do NOT create a new trial —
  // same hardware trying to "reinstall for a fresh trial" just gets its existing record back.

  return res.json({ device_id: device[0].device_id });
}));

/**
 * POST /license/verify
 * Called on every app launch AND periodically while running (heartbeat).
 * Returns a SIGNED verdict. Client cannot alter it without breaking the signature.
 */
router.post('/license/verify', asyncRoute(async (req, res) => {
  const { device_id, client_claimed_time } = req.body;
  if (!device_id) return res.status(400).json({ error: 'device_id required' });

  const rows = await db.query(
    `SELECT l.*, d.hw_fingerprint FROM licenses l
     JOIN devices d ON d.device_id = l.device_id
     WHERE l.device_id = ? ORDER BY l.created_at DESC LIMIT 1`,
    [device_id]
  );
  if (rows.length === 0) return res.status(404).json({ error: 'unknown device, call /license/register first' });

  const license = rows[0];
  const serverNow = new Date(); // <-- the ONLY time that matters, never client_claimed_time

  let status = license.status;
  let plan_type = license.plan_type;
  let expires_at = null;

  if (plan_type === 'trial') {
    const trialEnd = new Date(license.trial_started_at);
    trialEnd.setDate(trialEnd.getDate() + license.trial_days);
    expires_at = trialEnd.toISOString();
    if (serverNow > trialEnd) {
      status = 'expired';
      plan_type = 'expired';
    }
  } else if (plan_type === 'paid') {
    expires_at = license.paid_expiry_at ? new Date(license.paid_expiry_at).toISOString() : null;
    if (license.paid_expiry_at && serverNow > new Date(license.paid_expiry_at)) {
      status = 'expired';
    }
  }
  // 'blocked' status is set manually (e.g. chargeback, abuse) and always wins — not overridden here.
  if (license.status === 'blocked') status = 'blocked';

  // Persist any status transition (trial -> expired etc.)
  if (status !== license.status || plan_type !== license.plan_type) {
    await db.query('UPDATE licenses SET status = ?, plan_type = ? WHERE license_id = ?', [
      status, plan_type, license.license_id,
    ]);
  }

  // Log heartbeat — server_time is authoritative, client_claimed_time only logged for anomaly detection
  await db.query(
    `INSERT INTO license_heartbeats (license_id, device_id, server_time, client_claimed_time, ip_address)
     VALUES (?, ?, ?, ?, ?)`,
    [license.license_id, device_id, serverNow, client_claimed_time || null, req.ip]
  );

  // Anomaly signal (optional): if client_claimed_time is wildly behind server time,
  // it suggests clock rollback. We don't need to act on it here — the client-side
  // grace-period check (using signed server_time, not its own clock) already handles this.

  const verdict = signVerdict({
    device_id,
    license_id: license.license_id,
    status,
    plan_type,
    expires_at,
    server_time: serverNow.toISOString(),
    nonce: crypto.randomBytes(8).toString('hex'), // prevents replaying an old signed verdict indefinitely
  });

  return res.json(verdict);
}));

module.exports = router;
